ï¼ƒæ–‡ä»¶ï¼š.github / workflows / repo-sync.yml
åç§°ï¼šğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
ä¸Šï¼š
  æ—¶é—´è¡¨ï¼š
    -cronï¼šâ€œ 0/20 1-4,11-14 * * *â€
  å·¥ä½œæµç¨‹è°ƒåº¦ï¼š
  çœ‹ï¼š
    ç±»å‹ï¼šå¼€å§‹
  repository_dispatchï¼š
    ç±»å‹ï¼šrepo-sync
èŒä½ï¼š
  å›è´­åŒæ­¥ï¼š
    ç¯å¢ƒï¼š
      PATï¼š$ {{github.event.client_payload.PAT || secrets.PAT}}ï¼ƒæ­¤å¤„PATéœ€è¦ç”³è¯·ï¼Œæ•™ç¨‹è¯¦è§ï¼šhttpsï¼š//www.jianshu.com/p/bb82b3ad1d11
      dst_keyï¼š$ {{secrets.GITEE_PRIVATE_KEY}}ï¼ƒæˆ‘è‡ªå·±åŒæ­¥åˆ°giteeä½¿ç”¨ï¼Œå…¶ä»–äººå¯å¿½ç•¥
    è¿è¡Œï¼šubuntu-latest
    å¦‚æœï¼šgithub.event.repository.owner.id == github.event.sender.id
    è„šæ­¥ï¼š
      -ç”¨é€”ï¼šactions / checkout @ v2
        ä¸ï¼š
          æŒä¹…å‡­è¯ï¼šfalse

      -åç§°ï¼šå¼€å§‹ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
        ç”¨é€”ï¼šrepo-sync / github-sync @ v2
        å¦‚æœï¼šenv.PAT
        ä¸ï¼š
          source_repoï¼šâ€œ https://github.com/shuye72/MyActions.gitâ€
          source_branchï¼šâ€œä¸»è¦â€
          destination_branchï¼šâ€œä¸»è¦â€
          github_tokenï¼š$ {{github.event.client_payload.PAT || secrets.PAT}}
      ï¼ƒæˆ‘è‡ªå·±åŒæ­¥åˆ°giteeä½¿ç”¨ï¼Œå…¶ä»–äººå¯å¿½ç•¥
      -åç§°ï¼šåŒæ­¥github-> gitee
        ç”¨é€”ï¼šYikun / hub-mirror-action @ master
        å¦‚æœï¼šenv.dst_key
        ä¸ï¼š
          srcï¼šgithub / shuye72
          dstï¼šgitee / shuye72
          static_listï¼šâ€œ MyActionsâ€
          dst_keyï¼š$ {{secrets.GITEE_PRIVATE_KEY}}
          dst_tokenï¼š$ {{secrets.GITEE_TOKEN}}
